In [9]:
import os
import pandas as pd
import glob
#list all csv files only
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

['11-10-22.csv',
 '11-11-22.csv',
 '11-12-22.csv',
 '11-13-22.csv',
 '11-14-22.csv',
 '11-15-22.csv',
 '11-16-22.csv',
 '11-18-22.csv',
 '11-19-22.csv',
 '11-20-22.csv',
 '11-21-22.csv',
 '11-22-22.csv',
 '11-24-22.csv',
 '11-8-22.csv',
 '11-9-22.csv']

In [10]:
df_append = pd.DataFrame()
#append all files together
for file in csv_files:
            df_temp = pd.read_csv(file)
            df_append = df_append.append(df_temp, ignore_index=True)
df_append

C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)
C:\Users\tgsud\AppData\Local\Temp\ipykernel_21376\3254637134.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_append = df_append.append(df_temp, ignore_index=True)

,Unnamed: 0,dispatch_date,dispatch_time,hour_,location_block,text_general_code,lat,lng
0,0,2022-08-22,18:31:00,NaN,8800 BLOCK BARTRAM AV,Thefts,39.886841,-75.247645
1,1,2022-10-07,17:12:00,NaN,8800 BLOCK BARTRAM AV,Thefts,39.886841,-75.247645
2,2,2022-08-17,23:14:00,NaN,8800 BLOCK BARTRAM AV,Theft from Vehicle,39.886841,-75.247645
3,3,2022-09-21,15:21:00,NaN,7000 BLOCK FRANKFORD AV,Thefts,40.033620,-75.046249
4,4,2022-09-22,15:46:00,NaN,7000 BLOCK FRANKFORD AV,Thefts,40.033620,-75.046249
...,...,...,...,...,...,...,...,...
1968843,128428,2022-11-08,09:32:00,NaN,2800 BLOCK S CAMAC ST,Motor Vehicle Theft,39.914039,-75.168773
1968844,128429,2022-11-04,17:10:00,NaN,5800 BLOCK WALTON AV,Fraud,39.951016,-75.240597
1968845,128430,2022-10-29,16:26:00,NaN,400 BLOCK E WISTER ST,Forgery and Counterfeiting,40.034719,-75.160468
1968846,128431,2022-11-04,12:01:00,NaN,5300 BLOCK SPRUCE ST,DRIVING UNDER THE INFLUENCE,39.954781,-75.229301
1968847,128432,2022-11-05,17:10:00,NaN,700 BLOCK ARCH ST,Other Assaults,39.953081,-75.152061

In [11]:
df_append = df_append.drop_duplicates()
df_append = df_append.drop(['Unnamed: 0','hour_'],axis=1)

In [12]:
df_append

,dispatch_date,dispatch_time,location_block,text_general_code,lat,lng
0,2022-08-22,18:31:00,8800 BLOCK BARTRAM AV,Thefts,39.886841,-75.247645
1,2022-10-07,17:12:00,8800 BLOCK BARTRAM AV,Thefts,39.886841,-75.247645
2,2022-08-17,23:14:00,8800 BLOCK BARTRAM AV,Theft from Vehicle,39.886841,-75.247645
3,2022-09-21,15:21:00,7000 BLOCK FRANKFORD AV,Thefts,40.033620,-75.046249
4,2022-09-22,15:46:00,7000 BLOCK FRANKFORD AV,Thefts,40.033620,-75.046249
...,...,...,...,...,...,...
1968843,2022-11-08,09:32:00,2800 BLOCK S CAMAC ST,Motor Vehicle Theft,39.914039,-75.168773
1968844,2022-11-04,17:10:00,5800 BLOCK WALTON AV,Fraud,39.951016,-75.240597
1968845,2022-10-29,16:26:00,400 BLOCK E WISTER ST,Forgery and Counterfeiting,40.034719,-75.160468
1968846,2022-11-04,12:01:00,5300 BLOCK SPRUCE ST,DRIVING UNDER THE INFLUENCE,39.954781,-75.229301
1968847,2022-11-05,17:10:00,700 BLOCK ARCH ST,Other Assaults,39.953081,-75.152061

In [13]:
df_append = df_append.sort_values(by=['dispatch_date'],ignore_index=True)
df_append

,dispatch_date,dispatch_time,location_block,text_general_code,lat,lng
0,2022-01-01,18:54:00,4900 BLOCK CITY AV,Other Assaults,40.000938,-75.226894
1,2022-01-01,01:30:00,5500 BLOCK BLAKEMORE ST,Robbery No Firearm,40.047554,-75.159111
2,2022-01-01,12:41:00,5100 BLOCK SHELDON ST,All Other Offenses,40.034408,-75.161368
3,2022-01-01,12:46:00,200 BLOCK W INDIANA AV,Weapon Violations,39.996044,-75.134438
4,2022-01-01,16:10:00,7700 BLOCK DELPHI PL,Thefts,39.905933,-75.244667
...,...,...,...,...,...,...
287167,2022-11-23,12:08:00,1900 BLOCK S FRONT ST,Thefts,39.923980,-75.147871
287168,2022-11-23,16:37:00,6300 BLOCK FARNSWORTH ST,Receiving Stolen Property,40.032938,-75.067356
287169,2022-11-23,10:38:00,3700 BLOCK RICHMOND ST,Aggravated Assault Firearm,39.989554,-75.089610
287170,2022-11-23,12:48:00,1900 BLOCK S 70TH ST,Weapon Violations,39.923734,-75.244582
287171,2022-11-23,13:20:00,8400 BLOCK CHIPPEWA RD,Other Assaults,40.064219,-75.225958

In [14]:
df_append.to_csv("Data merge.csv")